<a href="https://colab.research.google.com/github/shobhakhar/Springboard/blob/main/Keras_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
datafile = files.upload()

Saving Churn_Modeling.csv to Churn_Modeling.csv


In [2]:
import pandas as pd
df = pd.read_csv('Churn_Modeling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
df['Exited'].unique()

array([1, 0])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
x = df.iloc[:,3:13].values
y = df.iloc[:,13].values

In [7]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [9]:
import numpy
numpy.unique(x[:,1])

array(['France', 'Germany', 'Spain'], dtype=object)

In [10]:
import numpy
numpy.unique(x[:,2])

array(['Female', 'Male'], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [12]:
le = LabelEncoder()

In [13]:
x.shape

(10000, 10)

In [14]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [15]:
x[:,1]  = le.fit_transform(x[:,1])

In [16]:
x.shape

(10000, 10)

In [17]:
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [18]:
x[:,2]  = le.fit_transform(x[:,2])

In [19]:
x.shape

(10000, 10)

In [20]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [21]:
lst = []
sum = 0
for i in range(0,10):
    lst.append(len(numpy.unique(x[:,i])))
for i in lst:
    sum= sum+ i
print(sum)

16935


In [22]:
len(numpy.unique(x[:,2]))

2

In [23]:
x.shape

(10000, 10)

In [24]:
onehotencoder = OneHotEncoder()

In [25]:
x = onehotencoder.fit_transform(x).toarray()

In [26]:
x.shape

(10000, 16935)

In [27]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
x = x[:,1:]

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x1 = sc.fit_transform(x)

In [30]:
x1.shape

(10000, 16934)

In [31]:
x1

array([[-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005],
       [-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005],
       [-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005],
       ...,
       [-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005],
       [-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005],
       [-0.0100005, -0.0100005, -0.0100005, ..., -0.0100005, -0.0100005,
        -0.0100005]])

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x1, y, test_size = 0.2)

In [33]:
X_train.shape

(8000, 16934)

In [34]:
X_test.shape

(2000, 16934)

In [35]:
import keras

In [36]:
from keras.models import Sequential
from keras.layers import Dense

In [37]:
classifier = Sequential()

In [38]:
classifier.add(Dense(units = 6, kernel_initializer='uniform', activation='relu'))

In [39]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [40]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [41]:
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [42]:
classifier.fit(X_train, y_train, batch_size = 10, epochs =15)

Epoch 1/15
800/800 [==============================] - 3s 3ms/step - loss: 0.5845 - accuracy: 0.7773
Epoch 2/15
800/800 [==============================] - 2s 3ms/step - loss: 0.4691 - accuracy: 0.7995
Epoch 3/15
800/800 [==============================] - 2s 3ms/step - loss: 0.4098 - accuracy: 0.7937
Epoch 4/15
800/800 [==============================] - 2s 3ms/step - loss: 0.3358 - accuracy: 0.7951
Epoch 5/15
800/800 [==============================] - 2s 3ms/step - loss: 0.2870 - accuracy: 0.8337
Epoch 6/15
800/800 [==============================] - 2s 3ms/step - loss: 0.2803 - accuracy: 0.8463
Epoch 7/15
800/800 [==============================] - 2s 3ms/step - loss: 0.2694 - accuracy: 0.8491
Epoch 8/15
800/800 [==============================] - 2s 3ms/step - loss: 0.2722 - accuracy: 0.8497
Epoch 9/15
800/800 [==============================] - 2s 3ms/step - loss: 0.2648 - accuracy: 0.8503
Epoch 10/15
800/800 [==============================] - 2s 3ms/step - loss: 0.2646 - accuracy: 0.8495

In [43]:
y_pred = classifier.predict(X_test)

In [44]:
y_pred = (y_pred>.5)

In [45]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1528   59]
 [ 365   48]]
